<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new album';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php

$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

$body = $form->get('body');
$body->setAttribute('class', 'form-control');
$body->setAttribute('placeholder', 'Artist');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($album) ?>
    <?= $this->formElement($album) ?>
    <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($body) ?>
    <?= $this->formElement($body) ?>
    <?= $this->formElementErrors()->render($body, ['class' => 'help-block']) ?>
</div>

<?php

echo $this->formHidden($form->get('id'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();